/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LocationSegments, RouteRenderProps, } from "@stencil/router";
export namespace Components {
    interface IpAppAbout {
    }
    interface IpAppHome {
    }
    interface IpAppRoot {
    }
    interface IpStencilRouteListener {
        "props": RouteRenderProps | undefined;
    }
}
declare global {
    interface HTMLIpAppAboutElement extends Components.IpAppAbout, HTMLStencilElement {
    }
    var HTMLIpAppAboutElement: {
        prototype: HTMLIpAppAboutElement;
        new (): HTMLIpAppAboutElement;
    };
    interface HTMLIpAppHomeElement extends Components.IpAppHome, HTMLStencilElement {
    }
    var HTMLIpAppHomeElement: {
        prototype: HTMLIpAppHomeElement;
        new (): HTMLIpAppHomeElement;
    };
    interface HTMLIpAppRootElement extends Components.IpAppRoot, HTMLStencilElement {
    }
    var HTMLIpAppRootElement: {
        prototype: HTMLIpAppRootElement;
        new (): HTMLIpAppRootElement;
    };
    interface HTMLIpStencilRouteListenerElement extends Components.IpStencilRouteListener, HTMLStencilElement {
    }
    var HTMLIpStencilRouteListenerElement: {
        prototype: HTMLIpStencilRouteListenerElement;
        new (): HTMLIpStencilRouteListenerElement;
    };
    interface HTMLElementTagNameMap {
        "ip-app-about": HTMLIpAppAboutElement;
        "ip-app-home": HTMLIpAppHomeElement;
        "ip-app-root": HTMLIpAppRootElement;
        "ip-stencil-route-listener": HTMLIpStencilRouteListenerElement;
    }
}
declare namespace LocalJSX {
    interface IpAppAbout {
    }
    interface IpAppHome {
    }
    interface IpAppRoot {
    }
    interface IpStencilRouteListener {
        "onPageEnter"?: (event: CustomEvent<LocationSegments>) => void;
        "onPageLeave"?: (event: CustomEvent<LocationSegments>) => void;
        "props"?: RouteRenderProps | undefined;
    }
    interface IntrinsicElements {
        "ip-app-about": IpAppAbout;
        "ip-app-home": IpAppHome;
        "ip-app-root": IpAppRoot;
        "ip-stencil-route-listener": IpStencilRouteListener;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-app-about": LocalJSX.IpAppAbout & JSXBase.HTMLAttributes<HTMLIpAppAboutElement>;
            "ip-app-home": LocalJSX.IpAppHome & JSXBase.HTMLAttributes<HTMLIpAppHomeElement>;
            "ip-app-root": LocalJSX.IpAppRoot & JSXBase.HTMLAttributes<HTMLIpAppRootElement>;
            "ip-stencil-route-listener": LocalJSX.IpStencilRouteListener & JSXBase.HTMLAttributes<HTMLIpStencilRouteListenerElement>;
        }
    }
}
