/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  LocationSegments,
  RouteRenderProps,
} from '@stencil/router';
import {
  EventEmitter,
} from '@stencil/core';


export namespace Components {

  interface IpAppAbout {}
  interface IpAppAboutAttributes extends StencilHTMLAttributes {}

  interface IpAppHome {}
  interface IpAppHomeAttributes extends StencilHTMLAttributes {}

  interface IpAppRoot {}
  interface IpAppRootAttributes extends StencilHTMLAttributes {}

  interface IpStencilRouteListener {
    'props': RouteRenderProps | undefined;
  }
  interface IpStencilRouteListenerAttributes extends StencilHTMLAttributes {
    'onPageEnter'?: (event: CustomEvent<LocationSegments>) => void;
    'onPageLeave'?: (event: CustomEvent<LocationSegments>) => void;
    'props'?: RouteRenderProps | undefined;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IpAppAbout': Components.IpAppAbout;
    'IpAppHome': Components.IpAppHome;
    'IpAppRoot': Components.IpAppRoot;
    'IpStencilRouteListener': Components.IpStencilRouteListener;
  }

  interface StencilIntrinsicElements {
    'ip-app-about': Components.IpAppAboutAttributes;
    'ip-app-home': Components.IpAppHomeAttributes;
    'ip-app-root': Components.IpAppRootAttributes;
    'ip-stencil-route-listener': Components.IpStencilRouteListenerAttributes;
  }


  interface HTMLIpAppAboutElement extends Components.IpAppAbout, HTMLStencilElement {}
  var HTMLIpAppAboutElement: {
    prototype: HTMLIpAppAboutElement;
    new (): HTMLIpAppAboutElement;
  };

  interface HTMLIpAppHomeElement extends Components.IpAppHome, HTMLStencilElement {}
  var HTMLIpAppHomeElement: {
    prototype: HTMLIpAppHomeElement;
    new (): HTMLIpAppHomeElement;
  };

  interface HTMLIpAppRootElement extends Components.IpAppRoot, HTMLStencilElement {}
  var HTMLIpAppRootElement: {
    prototype: HTMLIpAppRootElement;
    new (): HTMLIpAppRootElement;
  };

  interface HTMLIpStencilRouteListenerElement extends Components.IpStencilRouteListener, HTMLStencilElement {}
  var HTMLIpStencilRouteListenerElement: {
    prototype: HTMLIpStencilRouteListenerElement;
    new (): HTMLIpStencilRouteListenerElement;
  };

  interface HTMLElementTagNameMap {
    'ip-app-about': HTMLIpAppAboutElement
    'ip-app-home': HTMLIpAppHomeElement
    'ip-app-root': HTMLIpAppRootElement
    'ip-stencil-route-listener': HTMLIpStencilRouteListenerElement
  }

  interface ElementTagNameMap {
    'ip-app-about': HTMLIpAppAboutElement;
    'ip-app-home': HTMLIpAppHomeElement;
    'ip-app-root': HTMLIpAppRootElement;
    'ip-stencil-route-listener': HTMLIpStencilRouteListenerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
